### ISSUE TITLE
[backend] feat : Intégrer directement les relations dans les réponses

### ISSUE THREAD

**Issue by NicoooM** [CharlesLambret/Rendu-React-MT4#11]
Exemple : Intégrer les pays dans les réponses API des athlètes

**Comment by NicoooM** [comment]
getathletes
getathlete/id

**Comment by CharlesLambret** [comment]
L'objet doit embarquer : nombre total de médailles, pour chaque médaille l'événement associé + l'année et la ville

**Comment by CharlesLambret** [comment]
Pour le getAll, il faut le pays et la discipline

**Comment by CharlesLambret** [comment]
> L'objet doit embarquer : nombre total de médailles, pour chaque médaille l'événement associé + l'année et la ville

Intégré

**Comment by CharlesLambret** [comment]
> Pour le getAll, il faut le pays et la discipline

Intégré
