### ISSUE TITLE
[backend] err : liste des requete a cleanup / organise

### ISSUE THREAD

**Issue by toutouff** [CharlesLambret/Rendu-React-MT4#8]

**Comment by toutouff** [comment]
# /backend/medaille/requet/get
deux route : 
```
/getmedals/:id
```
recoit en parametre l'id de l'athlete
**proposition** : la deplacer dans les route athelete ```/getathlete/athlete_id/medals ```

**Comment by CharlesLambret** [comment]
Je vais inclure les médailles de l'athlete directement dans son objet
